enableGlobalCache: true

# FIXME: Hack to make the CI happy; to remove as soon as we are using `workspace:*` in our deps instead of pin versions
enableImmutableInstalls: false

nodeLinker: node-modules

plugins:
  - path: ../../.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: ../../.yarn/releases/yarn-sources.cjs
