name: Unit tests

on: [push]

jobs:
  build:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: yarn
      - name: install, bootstrap
        run: |
          yarn install --immutable
          yarn bootstrap --core
      - name: test
        run: |
          yarn test --runInBand --ci
